# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 16:38
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('poster_path', models.TextField(max_length=100)),
                ('adult', models.BooleanField()),
                ('overview', models.TextField(max_length=300)),
                ('release_date', models.DateField()),
                ('original_title', models.TextField()),
                ('original_language', models.TextField()),
                ('title', models.TextField()),
                ('backdrop_path', models.TextField()),
                ('popularity', models.TextField()),
                ('vote_count', models.TextField()),
                ('video', models.BooleanField()),
                ('vote_average', models.TextField()),
                ('genre_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='MovieDetails',
            fields=[
                ('movie_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='moviesAPP.Movie')),
                ('backdrop_path', models.TextField(max_length=100)),
                ('original_title', models.TextField()),
                ('overview', models.TextField(max_length=300)),
                ('runtime', models.TextField()),
                ('vote_average', models.TextField()),
                ('production_company', models.TextField()),
                ('release_date', models.DateField()),
                ('cast', models.CharField(max_length=5000)),
            ],
        ),
    ]
